name: getx_covid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.1
  google_fonts: 2.2.0
  http: ^0.13.4
  intl: ^0.17.0
  salomon_bottom_bar: ^3.2.0
  image_picker: ^0.8.4+8
  skeletons: ^0.0.3
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
